### ISSUE TITLE
What is the minimum hardware requirements to run fastcomposer?

### ISSUE THREAD

**Issue by ninjasaid2k** [mit-han-lab/fastcomposer#1]

**Comment by tianweiy** [comment]
it takes around 6gb gpu memory for batch size=1 inference. the [gradio demo](https://github.com/mit-han-lab/fastcomposer/blob/main/demo/run_gradio.py) currently uses around 10 gb ram and you can reduce it to 6 by setting num_images_per_prompt=1 at https://github.com/mit-han-lab/fastcomposer/blob/e62a85108f722db7cd9cbb46e933f0c4e423f470/demo/run_gradio.py#L52
