### ISSUE TITLE
Error when running the train code

### ISSUE THREAD

**Issue by wangyePHD** [mit-han-lab/fastcomposer#10]
I find that I meet a error when I run the train script, "unrecognized arguments: --text_image_linking postfuse".  Why? can you help me?

**Comment by RobertLau666** [comment]
The author is missing the following code in file "fastcomposer/utils.py", just add the following code
    parser.add_argument(
        "--text_image_linking",
        type=str,
        default=None,
    )

Another easy problem to spot is the need to rename the folder "script" to "scripts", didn't the author see that?

**Comment by wangyePHD** [comment]
Yes，I also noticed them.  Maybe the author do not see that. Anyway, the problem has been solved. Thanks.

**Comment by tianweiy** [comment]
@RobertLau666 fixed, thank you for letting us know
