### ISSUE TITLE
Appendix

### ISSUE THREAD

**Issue by darkliang** [mit-han-lab/fastcomposer#11]
Hello, I saw that the paper claims that some details are in the appendix, but I can't find the appendix, can you provide it?

**Comment by tianweiy** [comment]
@darkliang  you can find it here 
[appendix.pdf](https://github.com/mit-han-lab/fastcomposer/files/12041144/appendix.pdf)

we will put on online soon. Thanks

**Comment by darkliang** [comment]
Thank a lot!

**Comment by tianweiy** [comment]
we plan to release the data + evaluation code but it is going to take some time to prepare. Send us an email if you want an earlier access. thanks
