### ISSUE TITLE
attention visualization

### ISSUE THREAD

**Issue by xiaoqian-shen** [mit-han-lab/fastcomposer#13]
Thank you for your excellent work and for sharing your code and checkpoints. Figure 4 in the main paper serves as a remarkable visualization example. I'm curious if it would be possible for you to share the code for generating cross attention visualization of each token. Much appreciated!

**Comment by LiXinghui-666** [comment]
> Thank you for your excellent work and for sharing your code and checkpoints. Figure 4 in the main paper serves as a remarkable visualization example. I'm curious if it would be possible for you to share the code for generating cross attention visualization of each token. Much appreciated!

I saw that you closed the question, I would like to ask how you finally visualized these attention maps. Can you share the code for generating cross attention visualization? Thank you!
