### ISSUE TITLE
Training speed too slow

### ISSUE THREAD

**Issue by zjuyb** [mit-han-lab/fastcomposer#16]
Incredible job, I want to replicate him, but the training speed is too slow.I would like to know the cost of training. I have four A100 cards and a total of 64 batches to train for 15k. The estimated time is 200h, I think it's too high. Is there an error somewhere?How long have you been training on 8 * A6000？

**Comment by tianweiy** [comment]
it should be much faster. we will look into this in the next few days, thanks

**Comment by zjuyb** [comment]
> 

Thank you for your reply. Looking forward to your survey results

**Comment by Guangxuan-Xiao** [comment]
On our 8xA6000 server, the training script runs at 3.15s/iteration.  Could you profile your code with tools like snakeviz to see the performance bottleneck?

**Comment by zjuyb** [comment]
<img width="960" alt="new" src="https://github.com/mit-han-lab/fastcomposer/assets/114975439/6385c30d-342e-4057-925a-f5946a9f830c">
My speed is around 4.7s/it,It doesn't seem quite right,the item method wastes a lot of time,but I still don't know how to solve itproblem is.

**Comment by zjuyb** [comment]
<img width="960" alt="new" src="https://github.com/mit-han-lab/fastcomposer/assets/114975439/81809dcf-3979-4346-b0e1-e0256ea52822">
Testing 100step ,my speed is only 4.5s/iteration, it seems that most of my time is wasted on the item function, but I still don't know how to correct it

**Comment by Guangxuan-Xiao** [comment]
Are you using SSD to store dataset? What's your num_workers setting?

**Comment by zjuyb** [comment]
Thank you for your reply. It may be a problem with my hard drive. After changing another SSD last week, the speed was 3.21s/iteration. In addition, I did not make any changes to the code (num_workers in the dataloader is still 0, and the changes to num_workers seem to have little impact on my speed).This speed may still be a bit slow for A100, Perhaps there are still some issues that I will continue to search for, but it is already within my acceptable range. Thank you.

**Comment by JoyHuYY1412** [comment]
> Thank you for your reply. It may be a problem with my hard drive. After changing another SSD last week, the speed was 3.21s/iteration. In addition, I did not make any changes to the code (num_workers in the dataloader is still 0, and the changes to num_workers seem to have little impact on my speed).This speed may still be a bit slow for A100, Perhaps there are still some issues that I will continue to search for, but it is already within my acceptable range. Thank you.

Hi Yiboo, have you tried to set the `accelerate config` in order to accelerate the training? What's more, could you please share how you generate the cProfile when running `bash scripts/run_inference.sh` in order for Snakeviz to visualize? I am not familiar with these tools, thank you so much if you can give me some advice.
