### ISSUE TITLE
Error when running run_gradio.py and run_inference.py

### ISSUE THREAD

**Issue by edtjulien** [mit-han-lab/fastcomposer#2]
Hey, thanks for this amazing model. Can't wait to try it. I followed all install instructions and I got this issue (this happened for run_gradio.py and run_inference.py):

(venv) root@9748a9e6d3f4:/workspace/fastcomposer# python demo/run_gradio.py --finetuned_model_path model/fastcomposer/pytorch_model.bin  --mixed_precision "fp16"

`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
Traceback (most recent call last):
  File "/workspace/fastcomposer/demo/run_gradio.py", line 138, in <module>
    demo = create_demo()
  File "/workspace/fastcomposer/demo/run_gradio.py", line 72, in create_demo
    model = ModelWrapper(convert_model_to_pipeline(args, accelerator.device))
  File "/workspace/fastcomposer/demo/pipeline.py", line 31, in convert_model_to_pipeline
    model.load_state_dict(
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FastComposerModel:
	Missing key(s) in state_dict: "vae.encoder.mid_block.attentions.0.to_q.weight", "vae.encoder.mid_block.attentions.0.to_q.bias", "vae.encoder.mid_block.attentions.0.to_k.weight", "vae.encoder.mid_block.attentions.0.to_k.bias", "vae.encoder.mid_block.attentions.0.to_v.weight", "vae.encoder.mid_block.attentions.0.to_v.bias", "vae.encoder.mid_block.attentions.0.to_out.0.weight", "vae.encoder.mid_block.attentions.0.to_out.0.bias", "vae.decoder.mid_block.attentions.0.to_q.weight", "vae.decoder.mid_block.attentions.0.to_q.bias", "vae.decoder.mid_block.attentions.0.to_k.weight", "vae.decoder.mid_block.attentions.0.to_k.bias", "vae.decoder.mid_block.attentions.0.to_v.weight", "vae.decoder.mid_block.attentions.0.to_v.bias", "vae.decoder.mid_block.attentions.0.to_out.0.weight", "vae.decoder.mid_block.attentions.0.to_out.0.bias". 
	Unexpected key(s) in state_dict: "vae.encoder.mid_block.attentions.0.query.weight", "vae.encoder.mid_block.attentions.0.query.bias", "vae.encoder.mid_block.attentions.0.key.weight", "vae.encoder.mid_block.attentions.0.key.bias", "vae.encoder.mid_block.attentions.0.value.weight", "vae.encoder.mid_block.attentions.0.value.bias", "vae.encoder.mid_block.attentions.0.proj_attn.weight", "vae.encoder.mid_block.attentions.0.proj_attn.bias", "vae.decoder.mid_block.attentions.0.query.weight", "vae.decoder.mid_block.attentions.0.query.bias", "vae.decoder.mid_block.attentions.0.key.weight", "vae.decoder.mid_block.attentions.0.key.bias", "vae.decoder.mid_block.attentions.0.value.weight", "vae.decoder.mid_block.attentions.0.value.bias", "vae.decoder.mid_block.attentions.0.proj_attn.weight", "vae.decoder.mid_block.attentions.0.proj_attn.bias". 

Any idea of the reason?

**Comment by tianweiy** [comment]
Hi @edtjulien , thank you for the interest. I think the loading issue is due to different diffuser version. Could you check your diffuser version? Ours are 0.16.1. note that the master branch of diffuser changes the attention interface, so that you will see these missing keys error.

**Comment by edtjulien** [comment]
That's work. Thanks!
