### ISSUE TITLE
Out-of-memory error for training on 80GB A100 GPUs

### ISSUE THREAD

**Issue by malteprinzler** [mit-han-lab/fastcomposer#25]
When I try to train the model on 80GB A100 GPUs, I still receive out-of-memory errors. Im suspecting that it has to do with differences in the package versions of my environment. Could you please run the following command on your conda environment and report the result for better reproducibility:

`conda env export -n fastcomposer > environment.yml`

Thank you very much!

**Comment by malteprinzler** [comment]
found a solution in https://github.com/mit-han-lab/fastcomposer/issues/26#issue-2007095881

**Comment by TimandXiyu** [comment]
@malteprinzler Hi, do you have some insights about when will the model converge? I found it taking quite long with A100 and I wonder if lowering the train_step can offer similar performance?
