### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by xiaoqian-shen** [mit-han-lab/fastcomposer#5]
Great work! Curious about when will the training code be released.

**Comment by tianweiy** [comment]
Thank you for the interest. Most of us are traveling and finalizing a few other project's.  It will be around mid to late June for the training code release.

**Comment by Guangxuan-Xiao** [comment]
Hi, the training code and data are available now: https://github.com/mit-han-lab/fastcomposer#training. Thank you again for staying tuned and let us know if you have any questions.

Best,
Guangxuan
