### ISSUE TITLE
The quality does not come out as good as the example.

### ISSUE THREAD

**Issue by SlZeroth** [mit-han-lab/fastcomposer#6]
I used https://github.com/mit-han-lab/fastcomposer to generate a two shot image by inserting two images, but it is difficult to get a successful picture. Is there anything I am mistaken or need to change?

**Comment by tianweiy** [comment]
the most important parameter is the alpha. For instance, the following set of images are all generated with alpha 0.6, all the other hyper-parameter are the same (20 step text only + 30 step subject-conditioned). 

<img width="457" alt="multiple" src="https://github.com/mit-han-lab/fastcomposer/assets/38497390/92ef1af0-9c61-49e4-aa30-36fde7354857">

**Comment by JPW0080** [comment]
Try changing the model in fastcomposer/fastcomposer/utils.py to something other than the default runwayml/stable-diffusion-1-5
icbinp_v6 non-cherry picked default setting results with source images that were 172x172
Japanese woodblock print prompting did not cooperate with the aforementioned model.

A man <A*> and a man <A*> in the snow
https://ibb.co/0V766qZ
https://ibb.co/Gnds0xW
https://ibb.co/3rqHLkm
https://ibb.co/Cbh52NP
https://ibb.co/B33kfqG
https://ibb.co/bHTGdDg
https://ibb.co/vDh7wtH
https://ibb.co/9cBTg1Q

A man <A*> and a woman <A*> in the snow
https://ibb.co/pnZPLXp
https://ibb.co/GRNQd0D
https://ibb.co/MhgbRtm
https://ibb.co/m4bR87M
https://ibb.co/dDz6CbD
https://ibb.co/qWXdqqt
https://ibb.co/kJHNdTP
https://ibb.co/G2Hb2ZF

A man <A*> and a woman <A*> water color painting
https://ibb.co/z6g9yHh
https://ibb.co/FWDYjTn
https://ibb.co/4mgFNcx
https://ibb.co/sPq8SQM
https://ibb.co/80cbf9z
https://ibb.co/19DYvLD
https://ibb.co/mDXt3NG
https://ibb.co/Hzm6LRf

A man <A*> and a woman <A*> standing in the garden
https://ibb.co/t8jDFnQ
https://ibb.co/bzBLTVt
https://ibb.co/svkGT8V
https://ibb.co/FxrTwMY
https://ibb.co/jTKvQq3
https://ibb.co/rMzyzjq
https://ibb.co/KmPgm4T
https://ibb.co/p3cp7MY

A woman <A*> and a woman <A*> gardening, backyard
https://ibb.co/GH53wX5
https://ibb.co/5rY5wgk
https://ibb.co/9YFyRgS
https://ibb.co/yNNkqjP
https://ibb.co/Dwy5smy
https://ibb.co/xDpD1k4
https://ibb.co/rQh6ZGN
https://ibb.co/tc0Fwtj

A woman <A*> and a woman <A*> in the jungle
https://ibb.co/741hMCF
https://ibb.co/vhC9wLp
https://ibb.co/8rGfWgf
https://ibb.co/R9YWGSW
https://ibb.co/DQNF4KH
https://ibb.co/b1PVjVs
https://ibb.co/TMZWG8t
https://ibb.co/0DpCgPW

**Comment by tianweiy** [comment]
> Japanese woodblock print prompting did not cooperate with the aforementioned model.

It probably needs smaller alpha. Some times this results in dissimilar figures but it works reasonably robust (you get at least 1-2 good example among 4). 

The following is with default settings (and 0.6 alpha)

![subject_0000_prompt_0006_instance_0000](https://github.com/mit-han-lab/fastcomposer/assets/38497390/5cb7ebfc-f58f-47d9-816a-b751a2fc6ff0)
![subject_0001_prompt_0006_instance_0000](https://github.com/mit-han-lab/fastcomposer/assets/38497390/e7607513-65d2-450e-8b2c-1ea7649752ce)
![subject_0001_prompt_0006_instance_0003](https://github.com/mit-han-lab/fastcomposer/assets/38497390/dfc299d1-1697-4766-a3b9-1a6de4125c8a)
![subject_0002_prompt_0006_instance_0000](https://github.com/mit-han-lab/fastcomposer/assets/38497390/3ef22eef-be4f-4698-a00c-65b5533297eb)
![subject_0002_prompt_0006_instance_0002](https://github.com/mit-han-lab/fastcomposer/assets/38497390/28a23f27-fae9-4254-8aed-d193d5b41621)
![subject_0003_prompt_0006_instance_0001](https://github.com/mit-han-lab/fastcomposer/assets/38497390/8776f288-1728-4f8f-a3ae-646983451460)

full list of predictions on test could be found at [URL](https://mitprod-my.sharepoint.com/:u:/g/personal/tianweiy_mit_edu/EVS0S2lLFgJNu_V0vAnGidgBeO52uXcJQzp6lQEZI6CSLA?e=2zVWe7)

**Comment by NaokiSato102** [comment]
Could you explain the method to change the model in more detail?
I tried using arguments that seemed appropriate, but it didn't work.

`--pretrained_model_name_or_path "D:\Programs_D\_MachineLearning\StableDiffusionModels\Online\CheckPoint\anything-v4.0.ckpt"`

```
OSError: It looks like the config file at 'D:\Programs_D\_MachineLearning\StableDiffusionModels\Online\CheckPoint\anything-v4.0.ckpt' is not a valid JSON file.
```

**Comment by JPW0080** [comment]
The script expects diffusers model, https://huggingface.co/spaces/diffusers/sd-to-diffusers
