### ISSUE TITLE
Where to assign value for "cross_attention_scores" when calculating the object localization loss?

### ISSUE THREAD

**Issue by Wuchuq** [mit-han-lab/fastcomposer#7]
<img width="813" alt="image" src="https://github.com/mit-han-lab/fastcomposer/assets/74027834/d19d5801-f5c3-4ebd-9c66-03d17b1e503c">
Thank you for your great work! I find that the cross_attention_scores is first initialized as {} in model.py but not assigned later, which results in error in calculating the object localization loss function. Can you tell me how to deal with that?

**Comment by Wuchuq** [comment]
> 

Got it ! Thank you.

**Comment by Wuchuq** [comment]
Sorry to bother you again. I observed that the shape of cross attention map in each layer is [batch * head, latent_shape, num_token], so how can we obtain the attention map shown in Figure 4 ?
<img width="1034" alt="image" src="https://github.com/mit-han-lab/fastcomposer/assets/74027834/ff22c40a-9b23-4ab9-ae38-40eb1ea3117c">

**Comment by tianweiy** [comment]
Thank you for the interest. We follow [P2P](https://github.com/google/prompt-to-prompt) to average the attention map across attention heads and denoising time steps. And we choose the layer ```up_blocks.1.attentions.0.transformer_blocks.0.attn2``` as we find it has the highest correlation with the semantics of an image.

**Comment by Wuchuq** [comment]
> 
Understand!
thanks

**Comment by Pratyushk2003** [comment]
unet.up_blocks[1].attentions[0].transformer_blocks[0].attn2(hidden_states = text_embeds)
where text_embeds are achieved from clip model and it shape is [batch_size,  n, 768]
Eg: shape of hidden_states = torch.Size([1, 10, 768])

Then it is giving an error "RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x768 and 1280x1280)"

**Comment by tanghengjian** [comment]
your hidden_states  shape 768 will be match to 1280, you can cat some dim or do similar option. 
ever met this error when i imply this code with sdxl pipe
